### PR TITLE
Fixed navwheel for mobile devices

### LINKED ISSUE #8: Make navwheel smaller for mobile devices
Reduce the size of the navwheel in home tab for mobile devices.

### PR DESCRIPTION
**Pull request by Signior-X**
Fixes #8 
Also, checked it in my mobile and inn different values of window sizes.

### CODE REVIEW

**Comment by abhigyank** [comment]
@Milind712000  @vsvipul  please review and merge.

**Comment by vsvipul** [comment]
@Signior-X  Please fix the conflicts and attach screenshots for how it looked before and after.

**Comment by Signior-X** [comment]
@vsvipul I have removed the conflict, and here are the images of before and after on mobile.

Before:
Screenshot_2020-05-25-12-32-45-498_com microsoft emmx


After making changes:
Screenshot_2020-05-25-12-34-36-888_com microsoft emmx

Certainly the whole view was getting disrupted, so this fits it according to the device width.

**Comment by vsvipul** [comment]
Good work @Signior-X !

**Pull request merged**
