### PR TITLE
Corrected mail Id in contact page

### LINKED ISSUE #23: Problem in contact page
The [at] should be replaced by @ in the html.
Also what is the spelling of technical? 
Screenshot (177)

The mail id below Technical Secretary.

### PR DESCRIPTION
**Pull request by Signior-X**
Spelling corrected and added @ instead of [at]
Also added option to direct mail.
Fixes #23

### CODE REVIEW

**Comment by Signior-X** [comment]
@abhigyank

**Comment by abhigyank** [comment]
[at] is intended to avoid bot crawling. [Read here](https://github.com/KamandPrompt/sntc/pull/19#issuecomment-632514220).
Could you change the PR to fix the typo in technical? Then we can merge it!

**Comment by Signior-X** [comment]
Ya sure.

**Comment by Signior-X** [comment]
Done you can check now @abhigyank

**Comment by abhigyank** [comment]
Thanks @Signior-X :rocket:

**Pull request merged**
